#SPDX-License-Identifier: MIT-0
---
# handlers file for springPetClinic
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Spring PetClinic
  systemd:
    name: spring-petclinic
    state: restarted
    enabled: yes