#SPDX-License-Identifier: MIT-0
---
# tasks file for java21
- name: Install dependencies on Red Hat-based systems
  ansible.builtin.dnf:
    name:
      - "{{ java_package }}"
      - wget
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Install dependencies on Debian/Ubuntu-based systems
  ansible.builtin.apt:
    name:
      - "{{ java_package }}"
      - wget
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"