# The playbook.yml file should be located in the root directory alongside the springPetClinic role definition.

- name: Deploy Spring PetClinic
  hosts: redhat_nodes
  gather_facts: true
  become: yes
  vars_files:
    - tomcat10/vars/tomcat_manager.yml  

  roles:
    - springPetClinic
