# The playbook.yml file should be located in the root directory alongside the springPetClinic role definition.

- name: Deploy Spring PetClinic
  hosts: "{{ chosen_servers | default('redhat_nodes,ubuntu_nodes') }}"
  gather_facts: true
  become: yes
  vars_files:
    - tomcat10/vars/tomcat_manager.yml  

  roles:
    - springPetClinics

  post_tasks:
    - name: Display application URL
      debug:
        msg: >
          Spring PetClinic is available at
          http://{{ ansible_host | default(inventory_hostname) }}:{{ app_port }}