#SPDX-License-Identifier: MIT-0
---
# tasks file for springPetClinic

- name: Install Git dependency
  ansible.builtin.package:
    name: git
    state: present

- name: Clone Git repository
  ansible.builtin.git:
    repo: "{{ spring_pet_clinic_repo }}"
    dest: "{{ tomcat_home_directory }}/spring-petclinic"
    clone: true
    version: main
    update: true

- name: Ensure correct ownership on Spring PetClinic directory
  ansible.builtin.file:
    path: "{{ tomcat_home_directory }}/spring-petclinic"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    recurse: true
    state: directory

- name: Build application using Maven Wrapper
  ansible.builtin.command: ./mvnw package -DskipTests
  args:
    chdir: "{{ tomcat_home_directory }}/spring-petclinic"
  become: true
  become_user: "{{ user_name }}"

# - name: Add port 8082 to firewall permanently
#   ansible.builtin.command:
#     cmd: firewall-cmd --zone=public --add-port=8082/tcp --permanent

# - name: Reload firewalld
#   ansible.builtin.command:
#     cmd: firewall-cmd --reload

# The firewalld module is part of the ansible.posix collection and you need to install it.
# ansible-galaxy collection install ansible.posix add it to springPetClinic/meta/main.yml
# nohup (short for "no hangup") is a Linux and Unix command utility that runs a process or command even after you log out or disconnect from the terminal session

- name: Start Spring PetClinic application on port 8082
  ansible.builtin.shell: >
    nohup java -jar target/spring-petclinic-*.jar
    --server.port=8082
    > /var/log/spring-petclinic.log 2>&1 &
  args:
    chdir: "{{ tomcat_home_directory }}/spring-petclinic"
  become: true
  become_user: "{{ user_name }}"

- name: Allow port 8082 in firewalld
  ansible.posix.firewalld:
    port: 8082/tcp
    zone: public
    permanent: true
    state: enabled
    immediate: true